[versions]
bedrock-common = "2.9.17-SNAPSHOT"
geyser ="2.3.1-SNAPSHOT"
jackson = "2.14.0"
java-websocket = "1.5.3"
nimbus-jose-jwt = "9.23"
log4j = "2.20.0"
jline = "3.23.0"
terminalconsoleappender = "1.3.0"
methanol = "1.7.0"
minecraftauth = "4.0.3-SNAPSHOT"
gson = "2.11.0"

shadow = "8.1.1"
indra = "3.1.3"
blossom = "2.1.0"

[libraries]
bedrock-common = { group = "com.nukkitx.protocol", name = "bedrock-common", version.ref = "bedrock-common" }
geyser-api = { group = "org.geysermc.geyser", name = "api", version.ref = "geyser" }
geyser-core = { group = "org.geysermc.geyser", name = "core", version.ref = "geyser" }

jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson" }
jackson-dataformat-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version.ref = "jackson" }

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson"}

java-websocket = { group = "org.java-websocket", name = "Java-WebSocket", version.ref = "java-websocket" }
nimbus-jose-jwt = { group = "com.nimbusds", name = "nimbus-jose-jwt", version.ref = "nimbus-jose-jwt" }
shadow = { group = "com.github.johnrengelman", name = "shadow", version.ref = "shadow" }

terminalconsoleappender = { group = "net.minecrell", name = "terminalconsoleappender", version.ref = "terminalconsoleappender" }

log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
log4j-slf4j2-impl = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4j" }

jline-terminal = { group = "org.jline", name = "jline-terminal", version.ref = "jline" }
jline-terminal-jna = { group = "org.jline", name = "jline-terminal-jna", version.ref = "jline" }
jline-reader = { group = "org.jline", name = "jline-reader", version.ref = "jline" }

methanol = { group = "com.github.mizosoft.methanol", name = "methanol", version.ref = "methanol" }

minecraftauth = { group = "net.raphimc", name = "MinecraftAuth", version.ref = "minecraftauth" }

[bundles]
jackson = [
    "jackson-core",
    "jackson-dataformat-yaml"
]
geyser = [
    "geyser-api",
    "geyser-core"
]
log4j = [
    "log4j-api",
    "log4j-core",
    "log4j-slf4j2-impl"
]
jline = [
    "jline-terminal",
    "jline-terminal-jna",
    "jline-reader"
]

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
indra-git = { id = "net.kyori.indra.git", version.ref = "indra" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }