name: Build Pull Request

on: 
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'egg-m-c-xbox-broadcast.json'
      - 'LICENSE'
      - 'README.md'

jobs:
  build-ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm ci
      working-directory: bootstrap\manager\src\ui
    - name: Build
      run: npm run build
      working-directory: bootstrap\manager\src\ui
    - uses: actions/upload-artifact@v3
      if: success()
      with:
        name: UI
        path: bootstrap\manager\src\ui\dist
        if-no-files-found: error

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download UI
        uses: actions/download-artifact@v3
        with:
          name: UI
          path: bootstrap/manager/src/main/resources/static
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          gradle-home-cache-cleanup: true
      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: MCXboxBroadcastExtension
          path: bootstrap/geyser/build/libs/MCXboxBroadcastExtension.jar
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: MCXboxBroadcastStandalone
          path: bootstrap/standalone/build/libs/MCXboxBroadcastStandalone.jar
          if-no-files-found: error